'use client';
import DisclosureSection from './DisclosureSection';
import { sanitizeArtworkSvg } from '@/lib/layout/artwork';
import type { ArtworkElement } from '@/lib/layout/types';
const button='rounded-md border border-slate-300 bg-white px-3 py-1.5 text-sm hover:bg-slate-50';
const Toggle=({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void})=><label className="flex items-center justify-between gap-3 text-sm text-slate-700"><span>{label}</span><input type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)} className="accent-indigo-600"/></label>;
export default function ArtworkSettingsPanel({element,onChange}:{element:ArtworkElement;onChange:(element:ArtworkElement)=>void}){
  const replace=async(file:File)=>{try{const document=sanitizeArtworkSvg(await file.text()),intrinsicAspectRatio=document.viewBox.width/document.viewBox.height;onChange({...element,sourceFilename:file.name,document,intrinsicAspectRatio});}catch(error){window.alert(error instanceof Error?error.message:'Could not import SVG.');}};
  const reset=()=>{const cx=element.frame.x+element.frame.width/2,cy=element.frame.y+element.frame.height/2,width=element.frame.width,height=width/element.intrinsicAspectRatio;onChange({...element,frame:{x:cx-width/2,y:cy-height/2,width,height}});};
  return <><DisclosureSection title="Artwork" defaultOpen><div className="space-y-3"><div><div className="text-xs font-medium text-slate-500">Source</div><div className="truncate text-sm">{element.sourceFilename}</div></div>{element.document.warning&&<p className="text-xs text-amber-700">{element.document.warning}</p>}<label className={`${button} inline-block cursor-pointer`}>Replace SVG<input className="sr-only" type="file" accept=".svg,image/svg+xml" onChange={event=>{const file=event.target.files?.[0];if(file)void replace(file);event.target.value='';}}/></label><Toggle label="Lock proportions" checked={element.settings.lockProportions} onChange={lockProportions=>onChange({...element,settings:{...element.settings,lockProportions}})}/><button type="button" className={button} onClick={reset}>Reset proportions</button></div></DisclosureSection><DisclosureSection title="Appearance" defaultOpen><label className="space-y-1 text-xs font-medium text-slate-600">Opacity <span className="float-right">{element.settings.opacity}%</span><input className="w-full accent-indigo-600" type="range" min="0" max="100" step="1" value={element.settings.opacity} onChange={event=>onChange({...element,settings:{...element.settings,opacity:Number(event.target.value)}})}/></label></DisclosureSection><DisclosureSection title="Occlusion"><div className="space-y-3"><Toggle label="Occlude lower layers" checked={element.settings.occludeLowerLayers} onChange={occludeLowerLayers=>onChange({...element,settings:{...element.settings,occludeLowerLayers}})}/><div><Toggle label="Occlude closed shapes/paths" checked={element.settings.occludeClosedShapes} onChange={occludeClosedShapes=>onChange({...element,settings:{...element.settings,occludeClosedShapes}})}/><p className="mt-1 text-xs text-slate-500">Reserve the inside of closed vector shapes even when the artwork itself is outline-only.</p></div></div></DisclosureSection></>;
}
