'use client';
import GuidelinesSettingsPanel from '@/components/guidelines/GuidelinesSettingsPanel';
import { PAPERS_MM, type Orientation, type PaperId } from '@/lib/curve-helpers';
import { alignContent, halfPageContent, pageContentRect, type Alignment } from '@/lib/layout/geometry';
import { pageSize, type LayoutElement, type PageElement } from '@/lib/layout/types';

const input='w-full rounded-md border border-slate-300 px-2 py-1.5 text-sm';
const smallButton='rounded-md border border-slate-300 bg-white px-3 py-1.5 text-sm hover:bg-slate-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500';
function MillimetreField({label,value,onChange,min}:{label:string;value:number;onChange:(value:number)=>void;min?:number}) { return <label className="space-y-1 text-xs font-medium capitalize text-slate-600">{label}<div className="relative"><input className={input} type="number" step=".5" min={min} value={value} onChange={e=>{const next=Number(e.target.value);if(Number.isFinite(next)&&(min===undefined||next>=min))onChange(next);}}/><span className="pointer-events-none absolute right-2 top-1.5 text-slate-400">mm</span></div></label>; }

export default function LayoutInspector({ element, page, onChange }: { element:LayoutElement;page:PageElement;onChange:(element:LayoutElement)=>void }) {
  const patchFrame=(key:'x'|'y'|'width'|'height',value:number)=>onChange({...element,frame:{...element.frame,[key]:value}});
  const pageRect=pageContentRect(pageSize(page),page.settings.margins);
  const align=(alignment:Alignment)=>{if(element.type==='guidelines')onChange({...element,frame:alignContent(element.frame,element.settings.margins,pageRect,alignment)});};
  const half=(axis:'width'|'height')=>{if(element.type==='guidelines')onChange({...element,frame:halfPageContent(element.frame,element.settings.margins,pageRect,axis)});};
  return <section className="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200"><h2 className="font-semibold text-slate-800">Settings</h2><h3 className="mt-3 text-base font-semibold">{element.name}</h3>
    {element.type==='page'?<div className="mt-4 space-y-4"><div className="space-y-3"><h4 className="text-sm font-semibold">Page</h4><label className="block space-y-1 text-xs font-medium text-slate-600">Paper size<select className={input} value={element.settings.paper} onChange={e=>{const paper=e.target.value as PaperId;const settings={...element.settings,paper,orientation:PAPERS_MM[paper].defaultOrientation};const size=pageSize({...element,settings});onChange({...element,settings,frame:{x:0,y:0,...size}});}}>{Object.entries(PAPERS_MM).map(([id,paper])=><option key={id} value={id}>{paper.label}</option>)}</select></label><label className="block space-y-1 text-xs font-medium text-slate-600">Orientation<select className={input} value={element.settings.orientation} onChange={e=>{const settings={...element.settings,orientation:e.target.value as Orientation};const size=pageSize({...element,settings});onChange({...element,settings,frame:{x:0,y:0,...size}});}}><option value="portrait">Portrait</option><option value="landscape">Landscape</option></select></label></div>
      <div className="border-t border-slate-200 pt-4"><h4 className="text-sm font-semibold">Page margins</h4><div className="mt-3 grid grid-cols-2 gap-3">{(['top','right','bottom','left'] as const).map(key=><MillimetreField key={key} label={key} min={0} value={element.settings.margins[key]} onChange={value=>onChange({...element,settings:{...element.settings,margins:{...element.settings.margins,[key]:value}}})}/>)}</div></div>
      <div className="border-t border-slate-200 pt-4"><h4 className="text-sm font-semibold">Centre lines</h4><div className="mt-3 space-y-2">{(['vertical','horizontal'] as const).map(key=><label key={key} className="flex items-center justify-between text-sm text-slate-700"><span>Show {key} centre line</span><input type="checkbox" className="accent-indigo-600" checked={element.settings.centerLines[key]} onChange={e=>onChange({...element,settings:{...element.settings,centerLines:{...element.settings.centerLines,[key]:e.target.checked}}})}/></label>)}</div></div>
    </div>:<><details open className="mt-4 rounded-lg border border-slate-200 p-3"><summary className="cursor-pointer font-semibold">Position &amp; Size</summary><div className="mt-3 grid grid-cols-2 gap-3">{(['x','y','width','height'] as const).map(key=><MillimetreField key={key} label={key} min={key==='width'||key==='height'?4:undefined} value={element.frame[key]} onChange={value=>patchFrame(key,value)}/>)}</div>{element.type==='guidelines'&&<><div className="mt-4"><div className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-500">Align</div><div className="grid grid-cols-3 gap-2">{([['left','←','Align left'],['h-center','↔','Align horizontal centre'],['right','→','Align right'],['top','↑','Align top'],['v-center','↕','Align vertical centre'],['bottom','↓','Align bottom']] as [Alignment,string,string][]).map(([action,symbol,title])=><button key={action} type="button" title={title} aria-label={title} onClick={()=>align(action)} className={smallButton}>{symbol}</button>)}</div></div><div className="mt-4"><div className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-500">Size</div><div className="grid grid-cols-2 gap-2"><button type="button" title="Set usable guideline width to half the usable page width" onClick={()=>half('width')} className={smallButton}>½ Page width</button><button type="button" title="Set usable guideline height to half the usable page height" onClick={()=>half('height')} className={smallButton}>½ Page height</button></div></div></>}</details>{element.type==='guidelines'?<GuidelinesSettingsPanel value={element.settings} onChange={settings=>onChange({...element,settings})}/>:<p className="mt-3 text-sm text-slate-600">Settings will be added in a later pass.</p>}</>}
  </section>;
}
