import { SCRIPT_DEFAULTS,offset,pointAt,type Pt } from '@/lib/curve-helpers';
import { buildCopperplateContext } from '@/lib/copperplate/context';
import { buildGuideSet,type GuideSet } from '@/lib/guides/guide-template';
import { measureRun } from '@/lib/measure/measure-run';
import { SCRIPT_PROFILES,type ScriptId } from '@/lib/scripts';
import { boundsOfPoints } from '@/lib/layout/geometry';
import type { Frame } from '@/lib/layout/types';
import type { CalligramAlign,CalligramSettings } from './settings';

export type CalligramPlace={ch:string;w:number;h:number;sMid:number};export type CalligramLayout={placements:CalligramPlace[];needed:number;overBy:number};
export function buildCircleBaseline(radiusMM:number,box:{w:number;h:number},startAngleDeg:number,direction:'cw'|'ccw'):Pt[]{const radius=Math.max(1,radiusMM),L=2*Math.PI*radius,N=Math.max(180,Math.min(1440,Math.round(L))),cx=box.w/2,cy=box.h/2,start=startAngleDeg*Math.PI/180,sign=direction==='cw'?1:-1,pts:Pt[]=[];for(let i=0;i<=N;i++){const s=i/N*L,theta=start+sign*s/radius;pts.push({x:cx+radius*Math.cos(theta),y:cy+radius*Math.sin(theta)});}return pts;}
export function avgRadiusFromCenter(pts:Pt[],box:{w:number;h:number},fallback=1){if(!pts.length)return fallback;return pts.reduce((sum,p)=>sum+Math.hypot(p.x-box.w/2,p.y-box.h/2),0)/pts.length;}
export function normalSignForBaseline(pts:Pt[],box:{w:number;h:number}):1|-1{return avgRadiusFromCenter(offset(pts,-1),box)>avgRadiusFromCenter(pts,box)?1:-1;}
export function snapRadiusToWholeSteps(radiusMM:number,stepMM:number){if(stepMM<=0)return radiusMM;const k=Math.max(1,Math.round(2*Math.PI*radiusMM/stepMM));return Number((k*stepMM/(2*Math.PI)).toFixed(3));}
const wrap=(s:number,L:number)=>L>0?((s%L)+L)%L:0;export const pointAtWrapped=(pts:Pt[],s:number,L:number)=>pointAt(pts,wrap(s,L));
export function bandPolygonD(g:{ascLine?:Pt[];descLine?:Pt[]}){if(!g.ascLine?.length||!g.descLine?.length)return'';return`M ${g.ascLine.map(p=>`${p.x},${p.y}`).join(' L ')} L ${[...g.descLine].reverse().map(p=>`${p.x},${p.y}`).join(' L ')} Z`;}
export function computeCalligramLayout(run:ReturnType<typeof measureRun>,baseline:Pt[],L:number,xMM:number,nibMM:number,capMM:number,script:ScriptId,align:CalligramAlign):CalligramLayout{const glyphs=run.glyphs;const place=(adv:number[])=>{const total=adv.reduce((a,v)=>a+v,0);let cursor=align==='center'?Math.max(0,(L-total)/2):align==='end'?Math.max(0,L-total):0;const placements:CalligramPlace[]=[];glyphs.forEach((g,i)=>{const a=adv[i]??g.advMM;if(g.kind==='space'){cursor+=a;return;}placements.push({ch:g.ch,w:g.wMM,h:g.ch>='A'&&g.ch<='Z'?capMM:xMM,sMid:cursor+g.wMM/2});cursor+=a;});return{placements,total};};const a1=glyphs.map(g=>g.advMM),p1=place(a1);if(!p1.placements.length||script==='Copperplate')return{placements:p1.placements,needed:p1.total,overBy:Math.max(0,p1.total-L)};const a2=[...a1];p1.placements.forEach((pl,i)=>{const nL=pointAtWrapped(baseline,pl.sMid-pl.w/2,L).n,nR=pointAtWrapped(baseline,pl.sMid+pl.w/2,L).n,turn=Math.acos(Math.max(-1,Math.min(1,nL.x*nR.x+nL.y*nR.y)))*180/Math.PI,t=Math.max(0,Math.min(1,(turn-6)/22)),extra=t*nibMM*.25*(.6+.4*Math.min(1,pl.h/xMM));if(extra>0){let k=0;for(let gi=0;gi<glyphs.length;gi++){if(glyphs[gi].kind==='space')continue;if(k++===i){if(gi<a2.length-1)a2[gi]+=extra;break;}}}});const p2=place(a2);return{placements:p2.placements,needed:p2.total,overBy:Math.max(0,p2.total-L)};}
const number=(v:string,f:number)=>{const n=parseFloat(v);return Number.isFinite(n)?n:f;};
type Band={enabled:boolean;baseline:Pt[];guideSet:GuideSet;layout:CalligramLayout;bandD:string;length:number;xMM:number;script:ScriptId};
export type CalligramModel={main:Band;inner:Band;outer:Band;bands:Band[];visualBounds:Frame;circleLength:number;scriptLength:number};
export function buildCalligramModel(box:{w:number;h:number},s:CalligramSettings):CalligramModel{const nib=number(s.nibText,4),rad=s.penAngleDeg*Math.PI/180,rat=s.copperplateRatioPreset==='3:2:3'?{d:3,x:2,a:3}:s.copperplateRatioPreset==='1:1:1'?{d:1,x:1,a:1}:s.copperplateRatioPreset==='custom'?{d:number(s.copperplateDescUnitsText,2),x:number(s.copperplateXUnitsText,1),a:number(s.copperplateAscUnitsText,2)}:{d:2,x:1,a:2};const calibration={enabled:s.useCalibration,calWordLowerMM:number(s.calWordLowerMM,NaN),calWordDoubleMM:number(s.calWordDoubleMM,NaN),userScaleFactor:s.userScaleFactor,userSpaceFactor:s.userSpaceFactor};
 const make=(enabled:boolean,radius:number,script:ScriptId,size:number,text:string):Band=>{const baseline=buildCircleBaseline(radius,box,s.startAngleDeg,s.direction),normalSign=normalSignForBaseline(baseline,box),effective=script==='Copperplate'?size:size*Math.cos(rad),xMM=script==='Copperplate'?size:s.xNib*size,asc=script==='Copperplate'?size*rat.a/rat.x:s.ascNib*size,desc=script==='Copperplate'?size*rat.d/rat.x:s.descNib*size,cap=script==='Copperplate'?xMM*1.05:(SCRIPT_DEFAULTS.TexturaQuadrata?.capHeight??7)*size,ctx=script==='Copperplate'?buildCopperplateContext({xHeightMM:size,capStyle:s.capStyle,calibration}).ctx:{xHeightMM:xMM,nibMM:effective,scale:1,spaceMult:1,capStyle:'simple' as const},run=measureRun(text,SCRIPT_PROFILES[script],ctx),L=2*Math.PI*radius,layout=computeCalligramLayout(run,baseline,L,xMM,effective,cap,script,s.align),guideSet=buildGuideSet(script==='Copperplate'?'copperplate':'blackletter',{baseline,xMM,ascMM:asc,descMM:desc,normalSign,tickStepMM:script==='Copperplate'?Math.max(xMM*.9,3):effective,tickAnchorS:layout.placements[0]?.sMid-layout.placements[0]?.w/2,actualNibMM:size,penAngleDeg:s.penAngleDeg,blackletterScript:script==='Copperplate'?undefined:script,constructionGuides:s.constructionGuides});return{enabled,baseline,guideSet,layout,bandD:bandPolygonD(guideSet),length:L,xMM,script};};
 const main=make(true,s.radiusMM,s.script,s.script==='Copperplate'?s.xHeightMM:nib,s.text),inner=make(s.innerEnabled,s.innerRadiusMM,s.innerScript,number(s.innerSizeText,2),s.innerText),outer=make(s.outerEnabled,s.outerRadiusMM,s.outerScript,number(s.outerSizeText,2),s.outerText),bands=[main,...(inner.enabled?[inner]:[]),...(outer.enabled?[outer]:[])],points=bands.flatMap(b=>[...b.guideSet.ascLine,...b.guideSet.waistLine,...b.guideSet.baseLine,...b.guideSet.descLine]);return{main,inner,outer,bands,visualBounds:boundsOfPoints(points),circleLength:main.length,scriptLength:main.layout.needed};}
