import type { ScriptId } from '@/lib/scripts';

export type CalligramAlign='start'|'center'|'end';
export type CalligramDirection='cw'|'ccw';
export type CalligramRatio='2:1:2'|'3:2:3'|'1:1:1'|'custom';
export type CalligramSettings={script:ScriptId;radiusMM:number;allowPartialNibWidths:boolean;highContrast:boolean;text:string;innerText:string;outerText:string;startAngleDeg:number;direction:CalligramDirection;align:CalligramAlign;xHeightMM:number;capStyle:'simple'|'flourished';nibText:string;penAngleDeg:35|40|45;xNib:number;ascNib:number;descNib:number;copperplateRatioPreset:CalligramRatio;copperplateDescUnitsText:string;copperplateXUnitsText:string;copperplateAscUnitsText:string;useCalibration:boolean;calWordLowerMM:string;calWordDoubleMM:string;userScaleFactor:number;userSpaceFactor:number;innerEnabled:boolean;innerScript:ScriptId;innerRadiusMM:number;innerSizeText:string;outerEnabled:boolean;outerScript:ScriptId;outerRadiusMM:number;outerSizeText:string;showBoxes:boolean;showSpanFill:boolean;transparentWhitespace:boolean};

export const CALLIGRAM_MAIN_DEFAULTS={Fraktur:{radiusMM:45,nibText:'4',penAngleDeg:40 as const,xNib:4.5,ascNib:2,descNib:2},TexturaQuadrata:{radiusMM:45,nibText:'4',penAngleDeg:45 as const,xNib:5,ascNib:2,descNib:2},Copperplate:{radiusMM:60,nibText:'4',penAngleDeg:45 as const,xHeightMM:6,ratio:'3:2:3' as const}};
export function createDefaultCalligramSettings():CalligramSettings{return{script:'TexturaQuadrata',radiusMM:CALLIGRAM_MAIN_DEFAULTS.TexturaQuadrata.radiusMM,allowPartialNibWidths:true,highContrast:false,text:'',innerText:'',outerText:'',startAngleDeg:-90,direction:'cw',align:'start',xHeightMM:6,capStyle:'flourished',nibText:'4',penAngleDeg:45,xNib:5,ascNib:2,descNib:2,copperplateRatioPreset:'3:2:3',copperplateDescUnitsText:'2',copperplateXUnitsText:'1',copperplateAscUnitsText:'2',useCalibration:false,calWordLowerMM:'',calWordDoubleMM:'',userScaleFactor:1,userSpaceFactor:1,innerEnabled:false,innerScript:'Fraktur',innerRadiusMM:21,innerSizeText:'2',outerEnabled:false,outerScript:'Fraktur',outerRadiusMM:80,outerSizeText:'2',showBoxes:false,showSpanFill:true,transparentWhitespace:true};}

export function calligramSettingsForScript(current:CalligramSettings,script:ScriptId):CalligramSettings{const d=CALLIGRAM_MAIN_DEFAULTS[script];return{...current,script,radiusMM:d.radiusMM,nibText:d.nibText,penAngleDeg:d.penAngleDeg,xNib:'xNib'in d?d.xNib:current.xNib,ascNib:'ascNib'in d?d.ascNib:current.ascNib,descNib:'descNib'in d?d.descNib:current.descNib,xHeightMM:'xHeightMM'in d?d.xHeightMM:current.xHeightMM,copperplateRatioPreset:'ratio'in d?d.ratio:current.copperplateRatioPreset,...(script==='Copperplate'?{innerRadiusMM:50,innerScript:'Copperplate' as const,innerSizeText:'3.5',outerRadiusMM:92,outerScript:'Copperplate' as const,outerSizeText:'3.5'}:script==='Fraktur'?{innerRadiusMM:21,innerScript:'Fraktur' as const,innerSizeText:'2',outerRadiusMM:78,outerScript:'Fraktur' as const,outerSizeText:'2'}:{innerRadiusMM:21,innerScript:'Fraktur' as const,innerSizeText:'2',outerRadiusMM:80,outerScript:'Fraktur' as const,outerSizeText:'2'})};}
