import GuideOverlay from '@/components/preview/GuideOverlay';
import { buildCalligramModel,pointAtWrapped,type CalligramModel } from '@/lib/calligram/model';
import type { CalligramSettings } from '@/lib/calligram/settings';

function BandDecorations({band,showSpan,showBoxes,prefix}:{band:CalligramModel['main'];showSpan:boolean;showBoxes:boolean;prefix:string}){if(!band.layout.placements.length)return null;const first=band.layout.placements[0],last=band.layout.placements.at(-1)!,start=first.sMid-first.w/2,end=last.sMid+last.w/2,steps=Math.max(24,Math.ceil((end-start)/2)),base=[],waist=[];for(let i=0;i<=steps;i++){const s=start+(end-start)*i/steps,b=pointAtWrapped(band.guideSet.baseLine,s,band.length),w=pointAtWrapped(band.guideSet.waistLine,s,band.length);base.push(b.p);waist.push(w.p);}const d=`M ${waist.map(p=>`${p.x},${p.y}`).join(' L ')} L ${base.reverse().map(p=>`${p.x},${p.y}`).join(' L ')} Z`;return <>{showSpan&&<path d={d} fill="rgba(148,163,184,.18)" stroke="rgba(100,116,139,.55)" strokeWidth=".35" vectorEffect="non-scaling-stroke"/>}{showBoxes&&band.layout.placements.map((pl,i)=>{const left=pl.sMid-pl.w/2,right=pl.sMid+pl.w/2,b0=pointAtWrapped(band.guideSet.baseLine,left,band.length).p,b1=pointAtWrapped(band.guideSet.baseLine,right,band.length).p,w1=pointAtWrapped(band.guideSet.waistLine,right,band.length).p,w0=pointAtWrapped(band.guideSet.waistLine,left,band.length).p;return <path key={`${prefix}-${i}`} d={`M ${w0.x},${w0.y} L ${w1.x},${w1.y} L ${b1.x},${b1.y} L ${b0.x},${b0.y} Z`} fill="rgba(16,185,129,.08)" stroke="#10b981" strokeWidth=".3" vectorEffect="non-scaling-stroke"/>})}</>}

export default function CalligramRenderer({box,settings,idPrefix,pageBackground,paddingMM=0,selected=false}:{box:{w:number;h:number};settings:CalligramSettings;idPrefix:string;pageBackground?:string;paddingMM?:number;selected?:boolean}){
 const model=buildCalligramModel(box,settings),underMain=`${idPrefix}-under-main`,paddingMask=`${idPrefix}-padding-ring`,inset=Math.max(1,paddingMM+1),b=model.visualBounds,maskBounds={x:b.x-inset,y:b.y-inset,width:b.width+2*inset,height:b.height+2*inset},rectD=`M ${maskBounds.x},${maskBounds.y} H ${maskBounds.x+maskBounds.width} V ${maskBounds.y+maskBounds.height} H ${maskBounds.x} Z`,guideWidth=settings.highContrast?.9:.55,grid=settings.highContrast?'#64748b':'#cbd5e1',style={thin:guideWidth,bold:guideWidth,colors:{thin:'#111827',bold:'#111827',frame:'transparent'},grid:{thin:.35,colors:{tick:grid}}};
 return <g><defs><clipPath id={underMain} clipPathUnits="userSpaceOnUse"><path d={`${rectD} ${model.main.bandD}`} fillRule="evenodd" clipRule="evenodd"/></clipPath>{paddingMM>0&&<mask id={paddingMask} maskUnits="userSpaceOnUse" {...maskBounds}><rect {...maskBounds} fill="black"/>{model.bands.map((band,i)=><path key={`expanded-${i}`} d={band.bandD} fill="white" stroke="white" strokeWidth={paddingMM*2} strokeLinejoin="round" strokeLinecap="round"/>)}{model.bands.map((band,i)=><path key={`original-${i}`} d={band.bandD} fill="black"/>)}</mask>}</defs>
  {pageBackground&&model.bands.map((band,i)=><path key={`knockout-${i}`} d={band.bandD} fill={pageBackground} stroke={pageBackground} strokeWidth={paddingMM*2} strokeLinejoin="round" strokeLinecap="round"/>)}
  {selected&&paddingMM>0&&<rect data-no-export="true" pointerEvents="none" {...maskBounds} fill="#6366f1" fillOpacity=".14" mask={`url(#${paddingMask})`}/>}
  <GuideOverlay guideSet={model.main.guideSet} style={style}/>
  <g clipPath={`url(#${underMain})`}>{model.inner.enabled&&<GuideOverlay guideSet={model.inner.guideSet} style={style}/>} {model.outer.enabled&&<GuideOverlay guideSet={model.outer.guideSet} style={style}/>}</g>
  <BandDecorations band={model.main} showSpan={settings.showSpanFill} showBoxes={settings.showBoxes} prefix={`${idPrefix}-main`}/>{model.inner.enabled&&<BandDecorations band={model.inner} showSpan={settings.showSpanFill} showBoxes={settings.showBoxes} prefix={`${idPrefix}-inner`}/>} {model.outer.enabled&&<BandDecorations band={model.outer} showSpan={settings.showSpanFill} showBoxes={settings.showBoxes} prefix={`${idPrefix}-outer`}/>}
  {model.bands.map((band,i)=><path key={`hit-${i}`} data-no-export="true" d={band.bandD} fill="transparent" pointerEvents="fill"/>)}
 </g>;
}
