'use client';
import { useMemo, useRef, useState } from 'react';
import type { Orientation, PaperId, PlannerElement, PlannerElementKind } from '@/lib/page-planner/types';
import { createElement, paperDimensions, PAPERS } from '@/lib/page-planner/defaults';
import PlannerStage from './PlannerStage';
import LayerPanel from './LayerPanel';
import ElementSettingsPanel from './ElementSettingsPanel';

function cleanExport(svg: SVGSVGElement, width: number, height: number) { const clone = svg.cloneNode(true) as SVGSVGElement; clone.querySelectorAll('[data-no-export="true"]').forEach(node => node.remove()); clone.setAttribute('xmlns', 'http://www.w3.org/2000/svg'); clone.setAttribute('width', `${width}mm`); clone.setAttribute('height', `${height}mm`); clone.setAttribute('viewBox', `0 0 ${width} ${height}`); return clone; }
export default function PagePlanner() {
  const [paper, setPaper] = useState<PaperId>('A4'); const [orientation, setOrientation] = useState<Orientation>('portrait');
  const size = paperDimensions(paper, orientation); const [elements, setElements] = useState<PlannerElement[]>(() => [createElement('page-guidelines')]); const [selectedId, setSelectedId] = useState<string | null>(elements[0].id); const svgRef = useRef<SVGSVGElement>(null);
  const selected = useMemo(() => elements.find(e => e.id === selectedId), [elements, selectedId]);
  const change = (id: string, patch: Partial<PlannerElement>) => setElements(items => items.map(el => el.id === id ? { ...el, ...patch } as PlannerElement : el));
  const add = (kind: PlannerElementKind) => { const el = createElement(kind, size.width, size.height); setElements(items => [...items, el]); setSelectedId(el.id); };
  const reorder = (id: string, direction: -1 | 1) => setElements(items => { const from = items.findIndex(e => e.id === id), to = from + direction; if (to < 0 || to >= items.length) return items; const next = [...items]; [next[from], next[to]] = [next[to], next[from]]; return next; });
  function downloadSvg() { if (!svgRef.current) return; const blob = new Blob([cleanExport(svgRef.current, size.width, size.height).outerHTML], { type: 'image/svg+xml' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `calligraphy-page-${paper.toLowerCase()}.svg`; a.click(); URL.revokeObjectURL(a.href); }
  function print() { if (!svgRef.current) return; const markup = cleanExport(svgRef.current, size.width, size.height).outerHTML; const win = window.open('', '_blank'); if (!win) return; win.document.write(`<!doctype html><title>Calligraphy page plan</title><style>@page{size:${size.width}mm ${size.height}mm;margin:0}html,body{margin:0;width:${size.width}mm;height:${size.height}mm}svg{display:block}</style>${markup}<script>onload=()=>print()<\/script>`); win.document.close(); }
  return <main className="min-h-screen bg-slate-50 text-slate-900"><header className="border-b border-slate-200 bg-white px-5 py-4"><div className="mx-auto flex max-w-[1600px] flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-indigo-600">Calligraphy tools</p><h1 className="text-2xl font-semibold">Page planner</h1><p className="text-sm text-slate-500">Compose printable guides, writing areas, and reserved decoration space.</p></div><div className="flex items-end gap-2"><label className="text-xs text-slate-600">Paper<select value={paper} onChange={e => setPaper(e.target.value as PaperId)} className="mt-1 block rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm">{Object.entries(PAPERS).map(([id, p]) => <option key={id} value={id}>{p.label}</option>)}</select></label><label className="text-xs text-slate-600">Orientation<select value={orientation} onChange={e => setOrientation(e.target.value as Orientation)} className="mt-1 block rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm"><option value="portrait">Portrait</option><option value="landscape">Landscape</option></select></label><button onClick={downloadSvg} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm">Export SVG</button><button onClick={print} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white">Print to scale</button></div></div></header><div className="mx-auto grid max-w-[1600px] gap-4 p-4 lg:grid-cols-[260px_minmax(0,1fr)_260px]"><LayerPanel elements={elements} selectedId={selectedId} onSelect={setSelectedId} onAdd={add} onChange={change} onMove={reorder} onDelete={id => { setElements(items => items.filter(e => e.id !== id)); if (selectedId === id) setSelectedId(null); }}/><PlannerStage width={size.width} height={size.height} elements={elements} selectedId={selectedId} onSelect={setSelectedId} onMove={(id, x, y) => change(id, { x, y })} svgRef={svgRef}/><ElementSettingsPanel element={selected} onChange={patch => selected && change(selected.id, patch)}/></div></main>;
}
