'use client';

import DisclosureSection from '@/components/layout/DisclosureSection';
import type { GuidelinesSettings } from '@/lib/guides/straight/settings';
import { SCRIPT_PROFILES, type ScriptId } from '@/lib/scripts';

const input = 'w-full rounded-md border border-slate-300 px-2 py-1.5 text-sm';
const label = 'space-y-1 text-xs font-medium text-slate-600';

function NumberField({ title, value, onChange, min = 0, step = .5, unit = 'mm' }: { title: string; value: number; onChange: (value: number) => void; min?: number; step?: number; unit?: string }) {
  return <label className={label}>{title}<div className="relative"><input className={input} type="number" value={value} min={min} step={step} onChange={event => { const next = Number(event.target.value); if (Number.isFinite(next) && next >= min) onChange(next); }} />{unit && <span className="pointer-events-none absolute right-2 top-1.5 text-slate-400">{unit}</span>}</div></label>;
}
function Toggle({ title, checked, onChange }: { title: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex items-center justify-between gap-3 text-sm text-slate-700"><span>{title}</span><input type="checkbox" checked={checked} onChange={event => onChange(event.target.checked)} className="accent-indigo-600" /></label>; }
function Range({ title, value, onChange, max = 1 }: { title: string; value: number; onChange: (value: number) => void; max?: number }) { return <label className={label}>{title}<span className="float-right tabular-nums">{value.toFixed(2)}</span><input className="w-full accent-indigo-600" type="range" min="0" max={max} step=".05" value={value} onChange={event => onChange(Number(event.target.value))} /></label>; }
function Color({ title, value, onChange }: { title: string; value: string; onChange: (value: string) => void }) { return <label className={label}>{title}<input className="h-9 w-full rounded border border-slate-300" type="color" value={value} onChange={event => onChange(event.target.value)} /></label>; }

export default function GuidelinesSettingsPanel({ value, onChange, paddingMM, onPaddingChange, allowPartialGuidelines, onAllowPartialGuidelinesChange }: { value: GuidelinesSettings; onChange: (value: GuidelinesSettings) => void; paddingMM: number; onPaddingChange: (value: number) => void; allowPartialGuidelines: boolean; onAllowPartialGuidelinesChange: (value: boolean) => void }) {
  const set = <K extends keyof GuidelinesSettings>(key: K, next: GuidelinesSettings[K]) => onChange({ ...value, [key]: next });
  const nested = <K extends 'margins' | 'slant' | 'grid' | 'appearance'>(key: K, patch: Partial<GuidelinesSettings[K]>) => set(key, { ...value[key], ...patch });
  const blackletter = value.script !== 'Copperplate';
  const sectionClass = 'xl:w-[300px] xl:self-start';
  return <div className="space-y-3 xl:contents">
    <DisclosureSection title="Basics" defaultOpen className={sectionClass}>
      <div className="grid grid-cols-2 gap-3"><label className={`${label} col-span-2`}>Script<select className={input} value={value.script} onChange={event => set('script', event.target.value as ScriptId)}>{Object.keys(SCRIPT_PROFILES).map(script => <option key={script}>{script}</option>)}</select></label>
        {blackletter ? <><NumberField title="Nib size" value={value.nibMM} onChange={next => set('nibMM', next)} /><label className={label}>Pen angle<select className={input} value={value.penAngleDeg} onChange={event => set('penAngleDeg', Number(event.target.value) as 35 | 40 | 45)}><option>35</option><option>40</option><option>45</option></select></label><NumberField title="X-height (nibs)" unit="" value={value.xNib} onChange={next => set('xNib', next)} /></> : <NumberField title="X-height" value={value.xHeightMM} onChange={next => set('xHeightMM', next)} />}<NumberField title="Row gap" value={value.rowGapMM} onChange={next => set('rowGapMM', next)} /><NumberField title="Padding" value={paddingMM} onChange={onPaddingChange} /><div className="col-span-2" title="When disabled, vertical resizing snaps to complete guideline rows."><Toggle title="Allow partial guidelines" checked={allowPartialGuidelines} onChange={onAllowPartialGuidelinesChange} /></div>
      </div>
    </DisclosureSection>
    <DisclosureSection title="Script Details" defaultOpen className="xl:w-[340px] xl:self-start"><div className="space-y-3">
      {!blackletter ? <><label className={label}>Ratio preset<select className={input} value={value.copperplateRatioPreset} onChange={event => set('copperplateRatioPreset', event.target.value as GuidelinesSettings['copperplateRatioPreset'])}>{['3:2:3', '2:1:2', '1:1:1', 'custom'].map(option => <option key={option}>{option}</option>)}</select></label>{value.copperplateRatioPreset === 'custom' && <div className="grid grid-cols-3 gap-2">{(['desc', 'x', 'asc'] as const).map(key => <NumberField key={key} title={key} unit="" value={value.copperplateUnits[key]} onChange={next => set('copperplateUnits', { ...value.copperplateUnits, [key]: next })} />)}</div>}<div className="grid grid-cols-2 gap-3"><NumberField title="Slant angle" unit="°" value={value.slant.angle} step={1} onChange={next => nested('slant', { angle: next })} /><NumberField title="Slant spacing" value={value.slant.spacingMM} onChange={next => nested('slant', { spacingMM: next })} /></div><Toggle title="Second slant" checked={value.slant.secondEnabled} onChange={next => nested('slant', { secondEnabled: next })} />{value.slant.secondEnabled && <NumberField title="Second angle" unit="°" value={value.slant.secondAngle} step={1} onChange={next => nested('slant', { secondAngle: next })} />}<Range title="Slant contrast" value={value.slant.contrast} onChange={next => nested('slant', { contrast: next })} /></> : <><div className="grid grid-cols-2 gap-3"><NumberField title="Ascender nibs" unit="" value={value.ascNib} onChange={next => set('ascNib', next)} /><NumberField title="Descender nibs" unit="" value={value.descNib} onChange={next => set('descNib', next)} /></div><label className={label}>Grid width<select className={input} value={value.grid.widthMode} onChange={event => nested('grid', { widthMode: event.target.value as 'actual' | 'effective' })}><option value="effective">Effective nib</option><option value="actual">Actual nib</option></select></label><Toggle title="Horizontal grid" checked={value.grid.horizontal} onChange={next => nested('grid', { horizontal: next })} /><Toggle title="Vertical grid" checked={value.grid.vertical} onChange={next => nested('grid', { vertical: next })} /><Toggle title="Nib angle guide" checked={value.grid.nibAngleGuide} onChange={next => nested('grid', { nibAngleGuide: next })} /><Range title="Grid contrast" value={value.grid.contrast} onChange={next => nested('grid', { contrast: next })} /><Range title="Grid thickness" value={value.grid.thickness} max={1.4} onChange={next => nested('grid', { thickness: next })} /></>}
    </div></DisclosureSection>
    <DisclosureSection title="Margins" defaultOpen className={sectionClass}><div className="grid grid-cols-2 gap-3">{(['top', 'bottom', 'left', 'right'] as const).map(key => <NumberField key={key} title={key[0].toUpperCase() + key.slice(1)} value={value.margins[key]} onChange={next => nested('margins', { [key]: next })} />)}</div></DisclosureSection>
    <DisclosureSection title="Guide appearance" className="xl:w-[340px] xl:self-start"><div className="space-y-3"><Toggle title="Baseline indicator" checked={value.appearance.baselineIndicator} onChange={next => nested('appearance', { baselineIndicator: next })} /><div className="grid grid-cols-2 gap-3"><Color title="Baseline" value={value.appearance.baselineColor} onChange={next => nested('appearance', { baselineColor: next })} /><Color title="Waistline" value={value.appearance.waistlineColor} onChange={next => nested('appearance', { waistlineColor: next })} /></div><Range title="X-line contrast" value={value.appearance.xLineContrast} onChange={next => nested('appearance', { xLineContrast: next })} /><Range title="X-line thickness" value={value.appearance.xLineThickness} max={1.8} onChange={next => nested('appearance', { xLineThickness: next })} /><NumberField title="Midpoint dash gap" value={value.appearance.midpointDashGap} onChange={next => nested('appearance', { midpointDashGap: next })} /><Range title="Midpoint dash contrast" value={value.appearance.midpointDashContrast} onChange={next => nested('appearance', { midpointDashContrast: next })} /><Toggle title="High contrast" checked={value.appearance.highContrast} onChange={next => nested('appearance', { highContrast: next })} /><Toggle title="Centre line" checked={value.appearance.centerLine} onChange={next => nested('appearance', { centerLine: next })} /></div></DisclosureSection>
  </div>;
}
