'use client';
import type { GuidelinesSettings } from '@/lib/guides/straight/settings';
import { SCRIPT_PROFILES, type ScriptId } from '@/lib/scripts';

const input = 'w-full rounded-md border border-slate-300 px-2 py-1.5 text-sm';
const label = 'space-y-1 text-xs font-medium text-slate-600';
function NumberField({ title, value, onChange, min=0, step=.5 }: { title:string;value:number;onChange:(n:number)=>void;min?:number;step?:number }) { return <label className={label}>{title}<div className="relative"><input className={input} type="number" value={value} min={min} step={step} onChange={e=>{const n=Number(e.target.value);if(Number.isFinite(n))onChange(n);}}/><span className="pointer-events-none absolute right-2 top-1.5 text-slate-400">mm</span></div></label>; }
function Toggle({ title, checked, onChange }:{title:string;checked:boolean;onChange:(v:boolean)=>void}) { return <label className="flex items-center justify-between gap-3 text-sm text-slate-700"><span>{title}</span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="accent-indigo-600"/></label>; }

export default function GuidelinesSettingsPanel({ value, onChange }: { value: GuidelinesSettings; onChange:(value:GuidelinesSettings)=>void }) {
  const set=<K extends keyof GuidelinesSettings>(key:K,next:GuidelinesSettings[K])=>onChange({...value,[key]:next});
  const nested=<K extends 'margins'|'slant'|'grid'|'appearance'>(key:K,patch:Partial<GuidelinesSettings[K]>)=>set(key,{...value[key],...patch});
  const black=value.script!=='Copperplate';
  return <div className="mt-4 space-y-3">
    <details open className="rounded-lg border border-slate-200 p-3"><summary className="cursor-pointer font-semibold">Basics</summary><div className="mt-3 grid grid-cols-2 gap-3">
      <label className={`${label} col-span-2`}>Script<select className={input} value={value.script} onChange={e=>set('script',e.target.value as ScriptId)}>{Object.keys(SCRIPT_PROFILES).map(script=><option key={script}>{script}</option>)}</select></label>
      {black?<><NumberField title="Nib size" value={value.nibMM} onChange={n=>set('nibMM',n)}/><label className={label}>Pen angle<select className={input} value={value.penAngleDeg} onChange={e=>set('penAngleDeg',Number(e.target.value) as 35|40|45)}><option>35</option><option>40</option><option>45</option></select></label><NumberField title="X-height (nibs)" value={value.xNib} step={.5} onChange={n=>set('xNib',n)}/></>:<NumberField title="X-height" value={value.xHeightMM} onChange={n=>set('xHeightMM',n)}/>}<NumberField title="Row gap" value={value.rowGapMM} onChange={n=>set('rowGapMM',n)}/>
    </div></details>
    <details open className="rounded-lg border border-slate-200 p-3"><summary className="cursor-pointer font-semibold">Margins</summary><div className="mt-3 grid grid-cols-2 gap-3">{(['top','bottom','left','right'] as const).map(key=><NumberField key={key} title={key[0].toUpperCase()+key.slice(1)} value={value.margins[key]} onChange={n=>nested('margins',{[key]:n})}/>)}</div></details>
    <details className="rounded-lg border border-slate-200 p-3"><summary className="cursor-pointer font-semibold">Script details</summary><div className="mt-3 space-y-3">
      {!black?<><label className={label}>Ratio preset<select className={input} value={value.copperplateRatioPreset} onChange={e=>set('copperplateRatioPreset',e.target.value as GuidelinesSettings['copperplateRatioPreset'])}>{['3:2:3','2:1:2','1:1:1','custom'].map(v=><option key={v}>{v}</option>)}</select></label>{value.copperplateRatioPreset==='custom'&&<div className="grid grid-cols-3 gap-2">{(['desc','x','asc'] as const).map(key=><NumberField key={key} title={key} value={value.copperplateUnits[key]} onChange={n=>set('copperplateUnits',{...value.copperplateUnits,[key]:n})}/>)}</div>}<div className="grid grid-cols-2 gap-3"><NumberField title="Slant angle" value={value.slant.angle} step={1} onChange={n=>nested('slant',{angle:n})}/><NumberField title="Slant spacing" value={value.slant.spacingMM} onChange={n=>nested('slant',{spacingMM:n})}/></div><Toggle title="Second slant" checked={value.slant.secondEnabled} onChange={v=>nested('slant',{secondEnabled:v})}/>{value.slant.secondEnabled&&<NumberField title="Second angle" value={value.slant.secondAngle} step={1} onChange={n=>nested('slant',{secondAngle:n})}/>}<Range title="Slant contrast" value={value.slant.contrast} onChange={n=>nested('slant',{contrast:n})}/></>:<><div className="grid grid-cols-2 gap-3"><NumberField title="Ascender nibs" value={value.ascNib} onChange={n=>set('ascNib',n)}/><NumberField title="Descender nibs" value={value.descNib} onChange={n=>set('descNib',n)}/></div><label className={label}>Grid width<select className={input} value={value.grid.widthMode} onChange={e=>nested('grid',{widthMode:e.target.value as 'actual'|'effective'})}><option value="effective">Effective nib</option><option value="actual">Actual nib</option></select></label><Toggle title="Horizontal grid" checked={value.grid.horizontal} onChange={v=>nested('grid',{horizontal:v})}/><Toggle title="Vertical grid" checked={value.grid.vertical} onChange={v=>nested('grid',{vertical:v})}/><Toggle title="Nib angle guide" checked={value.grid.nibAngleGuide} onChange={v=>nested('grid',{nibAngleGuide:v})}/><Range title="Grid contrast" value={value.grid.contrast} onChange={n=>nested('grid',{contrast:n})}/><Range title="Grid thickness" value={value.grid.thickness} max={1.4} onChange={n=>nested('grid',{thickness:n})}/></>}
    </div></details>
    <details className="rounded-lg border border-slate-200 p-3"><summary className="cursor-pointer font-semibold">Guide appearance</summary><div className="mt-3 space-y-3"><Toggle title="Baseline indicator" checked={value.appearance.baselineIndicator} onChange={v=>nested('appearance',{baselineIndicator:v})}/><div className="grid grid-cols-2 gap-3"><Color title="Baseline" value={value.appearance.baselineColor} onChange={v=>nested('appearance',{baselineColor:v})}/><Color title="Waistline" value={value.appearance.waistlineColor} onChange={v=>nested('appearance',{waistlineColor:v})}/></div><Range title="X-line contrast" value={value.appearance.xLineContrast} onChange={n=>nested('appearance',{xLineContrast:n})}/><Range title="X-line thickness" value={value.appearance.xLineThickness} max={1.8} onChange={n=>nested('appearance',{xLineThickness:n})}/><NumberField title="Midpoint dash gap" value={value.appearance.midpointDashGap} onChange={n=>nested('appearance',{midpointDashGap:n})}/><Range title="Midpoint dash contrast" value={value.appearance.midpointDashContrast} onChange={n=>nested('appearance',{midpointDashContrast:n})}/><Toggle title="High contrast" checked={value.appearance.highContrast} onChange={v=>nested('appearance',{highContrast:v})}/><Toggle title="Centre line" checked={value.appearance.centerLine} onChange={v=>nested('appearance',{centerLine:v})}/></div></details>
  </div>;
}
function Range({title,value,onChange,max=1}:{title:string;value:number;onChange:(n:number)=>void;max?:number}){return <label className={label}>{title} <span className="float-right tabular-nums">{value.toFixed(2)}</span><input className="w-full accent-indigo-600" type="range" min="0" max={max} step=".05" value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}
function Color({title,value,onChange}:{title:string;value:string;onChange:(v:string)=>void}){return <label className={label}>{title}<input className="h-9 w-full rounded border border-slate-300" type="color" value={value} onChange={e=>onChange(e.target.value)}/></label>}
