import type { Pt } from '../curve-helpers';
// @ts-expect-error Node's type-stripping test runner requires the source extension.
import { parseSvgPath } from '../borders/acanthus/renaissance/svg-path.ts';

export type CustomCurve={filename:string;/** Centred coordinates expressed as fractions of source width. */points:Pt[];aspectRatio:number};
type Matrix=[number,number,number,number,number,number];
const I:Matrix=[1,0,0,1,0,0];
const mul=(a:Matrix,b:Matrix):Matrix=>[a[0]*b[0]+a[2]*b[1],a[1]*b[0]+a[3]*b[1],a[0]*b[2]+a[2]*b[3],a[1]*b[2]+a[3]*b[3],a[0]*b[4]+a[2]*b[5]+a[4],a[1]*b[4]+a[3]*b[5]+a[5]];
const apply=(m:Matrix,p:Pt):Pt=>({x:m[0]*p.x+m[2]*p.y+m[4],y:m[1]*p.x+m[3]*p.y+m[5]});
function transform(value=''):Matrix{let out=I,match:RegExpExecArray|null;const re=/([a-zA-Z]+)\s*\(([^)]*)\)/g;while((match=re.exec(value))){const n=match[2].trim().split(/[\s,]+/).filter(Boolean).map(Number);if(n.some(v=>!Number.isFinite(v)))throw new Error('Invalid SVG transform.');let m:Matrix;switch(match[1].toLowerCase()){case'matrix':if(n.length!==6)throw new Error('Invalid SVG transform.');m=n as Matrix;break;case'translate':m=[1,0,0,1,n[0]??0,n[1]??0];break;case'scale':m=[n[0]??1,0,0,n[1]??n[0]??1,0,0];break;case'rotate':{const a=(n[0]??0)*Math.PI/180,c=Math.cos(a),s=Math.sin(a),r:Matrix=[c,s,-s,c,0,0];m=n.length>2?mul(mul([1,0,0,1,n[1],n[2]],r),[1,0,0,1,-n[1],-n[2]]):r;break;}case'skewx':m=[1,0,Math.tan((n[0]??0)*Math.PI/180),1,0,0];break;case'skewy':m=[1,Math.tan((n[0]??0)*Math.PI/180),0,1,0,0];break;default:throw new Error(`Unsupported SVG transform "${match[1]}".`);}out=mul(out,m);}return out;}
const attributes=(s:string)=>Object.fromEntries([...s.matchAll(/([:\w-]+)\s*=\s*(?:"([^"]*)"|'([^']*)')/g)].map(m=>[m[1].toLowerCase(),m[2]??m[3]??'']));
const cubic=(p0:Pt,p1:Pt,p2:Pt,p3:Pt)=>Array.from({length:41},(_,i)=>{const t=i/40,u=1-t;return{x:u**3*p0.x+3*u*u*t*p1.x+3*u*t*t*p2.x+t**3*p3.x,y:u**3*p0.y+3*u*u*t*p1.y+3*u*t*t*p2.y+t**3*p3.y};});

/** Extract one visible open path and discard all uploaded markup. */
export function importCustomCurveSvg(source:string,filename:string):CustomCurve{
 if(!/<svg\b/i.test(source))throw new Error('Not a valid SVG file.');
 const stack:{matrix:Matrix;hidden:boolean}[]=[{matrix:I,hidden:false}],paths:{d:string;matrix:Matrix}[]=[];
 for(const token of source.match(/<[^>]+>/g)??[]){if(/^<\s*[!?]/.test(token))continue;if(/^<\//.test(token)){if(stack.length>1)stack.pop();continue;}const tag=token.match(/^<\s*([\w:-]+)/)?.[1]?.toLowerCase();if(!tag)continue;const a=attributes(token),parent=stack.at(-1)!,style=(a.style??'').toLowerCase(),hidden=parent.hidden||['defs','clippath','mask','symbol'].includes(tag)||a.display==='none'||a.visibility==='hidden'||/display\s*:\s*none/.test(style)||/visibility\s*:\s*hidden/.test(style),matrix=mul(parent.matrix,transform(a.transform));if(tag==='path'&&!hidden&&(a.d??'').trim())paths.push({d:a.d,matrix});if(!/\/\s*>$/.test(token))stack.push({matrix,hidden});}
 if(!paths.length)throw new Error('Upload an SVG containing one open path.');if(paths.length!==1)throw new Error('SVG must contain exactly one visible path.');const{d,matrix}=paths[0];if((d.match(/[mM]/g)??[]).length!==1)throw new Error('Path must contain one continuous subpath.');let parsed:ReturnType<typeof parseSvgPath>;try{parsed=parseSvgPath(d);}catch{throw new Error('SVG path data is invalid or unsupported.');}if(parsed.closed||/[zZ]/.test(d))throw new Error('Custom curve must be an open path.');const points:Pt[]=[];for(const seg of parsed.segments){const part=cubic(seg.p0,seg.c1,seg.c2,seg.p1);if(points.length)part.shift();points.push(...part.map(p=>apply(matrix,p)));}if(points.some(p=>!Number.isFinite(p.x)||!Number.isFinite(p.y)))throw new Error('SVG path contains invalid coordinates.');const xs=points.map(p=>p.x),ys=points.map(p=>p.y),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),width=maxX-minX,length=points.slice(1).reduce((v,p,i)=>v+Math.hypot(p.x-points[i].x,p.y-points[i].y),0);if(width<1e-6||length<1e-6)throw new Error('SVG path must have a usable width and length.');const cx=(minX+maxX)/2,cy=(minY+maxY)/2;return{filename,points:points.map(p=>({x:(p.x-cx)/width,y:(p.y-cy)/width})),aspectRatio:(maxY-minY)/width};
}

export function fitCustomCurve(curve:CustomCurve,box:{w:number;h:number},scale=1,rotationDeg=0,flip=false):Pt[]{const width=box.w*.84,a=rotationDeg*Math.PI/180,c=Math.cos(a),s=Math.sin(a),cx=box.w/2,cy=box.h*.35;return curve.points.map(p=>{const x=p.x*width*scale,y=p.y*width*scale*(flip?-1:1);return{x:cx+x*c-y*s,y:cy+x*s+y*c};});}
