import { SCRIPT_DEFAULTS, buildPreset, lengthPoly, offset, pointAt, sample, transformCubic, type Pt, type PtCubic } from '@/lib/curve-helpers';
import { buildCopperplateContext } from '@/lib/copperplate/context';
import { buildGuideSet, type GuideSet } from '@/lib/guides/guide-template';
import { measureRun } from '@/lib/measure/measure-run';
import { SCRIPT_PROFILES, type ScriptId } from '@/lib/scripts';
import type { CurvedTitleAlign, CurvedTitleSettings } from './settings';
import { boundsOfPoints } from '@/lib/layout/geometry';
import type { Frame } from '@/lib/layout/types';

export type CurvedTitlePlace = { ch: string; w: number; h: number; sMid: number };
export type CurvedTitleLayout = { placements: CurvedTitlePlace[]; needed: number; overBy: number };
export type SpanPoly = { waistPts: Pt[]; basePts: Pt[] };

// Mechanically extracted from the standalone planner. The measured advances and
// blackletter turn-spacing compensation are intentionally unchanged.
export function computeCurvedTitleLayout(runData: ReturnType<typeof measureRun>, bandBaseline: Pt[], bandArcLen: number, bandXMM: number, bandNibMM: number, bandCapMM: number, scriptId: ScriptId, align: CurvedTitleAlign): CurvedTitleLayout {
  const glyphs=runData.glyphs;
  const placeWithAdvances=(advances:number[])=>{ const totalAdvance=advances.reduce((a,v)=>a+v,0); let s0=0; if(align==='center')s0=Math.max(0,(bandArcLen-totalAdvance)/2); if(align==='end')s0=Math.max(0,bandArcLen-totalAdvance); const placements:CurvedTitlePlace[]=[]; let cursor=s0; for(let i=0;i<glyphs.length;i++){const g=glyphs[i],adv=advances[i]??g.advMM;if(g.kind==='space'){cursor+=adv;continue;}const w=g.wMM,isCap=g.ch>='A'&&g.ch<='Z',h=isCap?bandCapMM:bandXMM;placements.push({ch:g.ch,w,h,sMid:cursor+w/2});cursor+=adv;}return{placements,totalAdvance};};
  const adv1=glyphs.map(g=>g.advMM),pass1=placeWithAdvances(adv1); if(!pass1.placements.length||scriptId==='Copperplate')return{placements:pass1.placements,needed:pass1.totalAdvance,overBy:Math.max(0,pass1.totalAdvance-bandArcLen)};
  const adv2=adv1.slice(); for(let i=0;i<pass1.placements.length;i++){const pl=pass1.placements[i],sMid=Math.min(bandArcLen,Math.max(0,pl.sMid)),sL=Math.max(0,Math.min(bandArcLen,sMid-pl.w/2)),sR=Math.max(0,Math.min(bandArcLen,sMid+pl.w/2)),nL=pointAt(bandBaseline,sL).n,nR=pointAt(bandBaseline,sR).n,dot=nL.x*nR.x+nL.y*nR.y,turnDeg=Math.acos(Math.max(-1,Math.min(1,dot)))*180/Math.PI,t=Math.max(0,Math.min(1,(turnDeg-6)/(28-6))),extra=t*bandNibMM*.25*(.6+.4*Math.min(1,pl.h/bandXMM));if(extra>0){let k=0;for(let gi=0;gi<glyphs.length;gi++){if(glyphs[gi].kind==='space')continue;if(k===i){if(gi<adv2.length-1)adv2[gi]+=extra;break;}k++;}}} const pass2=placeWithAdvances(adv2);return{placements:pass2.placements,needed:pass2.totalAdvance,overBy:Math.max(0,pass2.totalAdvance-bandArcLen)};
}

function flipCubicVertically(c:PtCubic,boxH:number):PtCubic{const f=(p:Pt)=>({x:p.x,y:boxH-p.y});const out:PtCubic={...c,p0:f(c.p0),p1:f(c.p1),p2:f(c.p2),p3:f(c.p3)};if(c._extraSegs?.length)out._extraSegs=c._extraSegs.map(seg=>[seg[0],boxH-seg[1],seg[2],boxH-seg[3],seg[4],boxH-seg[5],seg[6],boxH-seg[7]]);return out;}
function translateCubic(c:PtCubic,dx:number,dy:number):PtCubic{const t=(p:Pt)=>({x:p.x+dx,y:p.y+dy});const out:PtCubic={...c,p0:t(c.p0),p1:t(c.p1),p2:t(c.p2),p3:t(c.p3)};if(c._extraSegs?.length)out._extraSegs=c._extraSegs.map(s=>[s[0]+dx,s[1]+dy,s[2]+dx,s[3]+dy,s[4]+dx,s[5]+dy,s[6]+dx,s[7]+dy]);return out;}
const num=(text:string,fallback:number)=>{const v=parseFloat(text);return Number.isFinite(v)?v:fallback;};
const spanOf=(layout:CurvedTitleLayout,len:number)=>layout.placements.length?{sStart:Math.max(0,layout.placements[0].sMid-layout.placements[0].w/2),sEnd:Math.min(len,layout.placements.at(-1)!.sMid+layout.placements.at(-1)!.w/2)}:null;
const spanPolygon=(span:{sStart:number;sEnd:number}|null,base:Pt[],len:number,x:number,nib:number,script:ScriptId):SpanPoly|null=>{if(!span)return null;const ds=script==='Copperplate'?Math.max(.5,x*.2):Math.max(.5,nib*.5),waistPts:Pt[]=[],basePts:Pt[]=[];for(let s=span.sStart;s<=span.sEnd+.0001;s+=ds){const{p,n}=pointAt(base,Math.min(len,s));waistPts.push({x:p.x-n.x*x,y:p.y-n.y*x});basePts.push(p);}return{waistPts,basePts};};
const bandPoly=(a:Pt[],b:Pt[])=>`M ${a.map(p=>`${p.x},${p.y}`).join(' L ')} L ${[...b].reverse().map(p=>`${p.x},${p.y}`).join(' L ')} Z`;

export type CurvedTitleModel={baseline:Pt[];arcLen:number;layout:CurvedTitleLayout;guideSet:GuideSet;spanPoly:SpanPoly|null;midAscPts:Pt[]|null;midDescPts:Pt[]|null;top:{enabled:boolean;layout:CurvedTitleLayout;guideSet:GuideSet;arcLen:number;xMM:number;spanPoly:SpanPoly|null;clip:string};bottom:{enabled:boolean;layout:CurvedTitleLayout;guideSet:GuideSet;arcLen:number;xMM:number;spanPoly:SpanPoly|null;clip:string};xMM:number;script:ScriptId;curveLength:number;scriptLength:number;overBy:number;visualBounds:Frame;footprintD:string};

export function buildCurvedTitleModel(box:{w:number;h:number},s:CurvedTitleSettings):CurvedTitleModel{
  const nib=num(s.nibText,2),topSize=num(s.topBandSizeText,nib),bottomSize=num(s.bottomBandSizeText,nib),rad=s.penAngleDeg*Math.PI/180,effective=s.script==='Copperplate'?nib:nib*Math.cos(rad),effectiveTop=s.topBandScript==='Copperplate'?topSize:topSize*Math.cos(rad),effectiveBottom=s.bottomBandScript==='Copperplate'?bottomSize:bottomSize*Math.cos(rad);
  const units=s.copperplateRatioPreset==='custom'?{d:num(s.copperplateDescUnitsText,2),x:num(s.copperplateXUnitsText,1),a:num(s.copperplateAscUnitsText,2)}:s.copperplateRatioPreset==='3:2:3'?{d:3,x:2,a:3}:s.copperplateRatioPreset==='1:1:1'?{d:1,x:1,a:1}:{d:2,x:1,a:2};
  const copperHeights={xMM:s.xHeightMM,ascMM:s.xHeightMM*units.a/units.x,descMM:s.xHeightMM*units.d/units.x},blackHeights={xMM:s.xNib*nib,ascMM:s.ascNib*nib,descMM:s.descNib*nib},heights=s.script==='Copperplate'?copperHeights:blackHeights,{xMM,ascMM,descMM}=heights,capMM=s.script==='Copperplate'?s.xHeightMM*1.05:(SCRIPT_DEFAULTS.TexturaQuadrata?.capHeight??7)*nib;
  const calibration={enabled:s.useCalibration,calWordLowerMM:num(s.calWordLowerMM,NaN),calWordDoubleMM:num(s.calWordDoubleMM,NaN),userScaleFactor:s.userScaleFactor,userSpaceFactor:s.userSpaceFactor};
  const copper=buildCopperplateContext({xHeightMM:s.xHeightMM,capStyle:s.capStyle,calibration}); const ctx=s.script==='Copperplate'?copper.ctx:{xHeightMM:blackHeights.xMM,nibMM:effective,scale:1,spaceMult:1,capStyle:'simple' as const};const run=measureRun(s.text,SCRIPT_PROFILES[s.script],ctx);
  const bandRun=(text:string,script:ScriptId,size:number,eff:number)=>measureRun(text,SCRIPT_PROFILES[script],script==='Copperplate'?buildCopperplateContext({xHeightMM:size,capStyle:s.capStyle,calibration}).ctx:{xHeightMM:s.xNib*size,nibMM:eff,scale:1,spaceMult:1,capStyle:'simple'});
  let raw=buildPreset(s.curve,box);if(s.flipCurve){const flipped=flipCubicVertically(raw,box.h),dy=(raw.p0.y+raw.p3.y-flipped.p0.y-flipped.p3.y)/2;raw=translateCubic(flipped,0,dy);}const cubic=transformCubic(raw,box.w/2,box.h/2,s.scale/100,s.rotation);let base:Pt[]=[];if(cubic._extraSegs?.length){for(const seg of cubic._extraSegs){const pts=sample({x:seg[0],y:seg[1]},{x:seg[2],y:seg[3]},{x:seg[4],y:seg[5]},{x:seg[6],y:seg[7]},220);if(base.length)pts.shift();base.push(...pts);}}else base=sample(cubic.p0,cubic.p1,cubic.p2,cubic.p3,900);const xs=base.map(p=>p.x),center=(Math.min(...xs)+Math.max(...xs))/2,baseline=base.map(p=>({x:p.x+box.w/2-center,y:p.y})),arcLen=lengthPoly(baseline),layout=computeCurvedTitleLayout(run,baseline,arcLen,xMM,effective,capMM,s.script,s.align),span=spanOf(layout,arcLen),guideSet=buildGuideSet(s.script==='Copperplate'?'copperplate':'blackletter',{baseline,xMM,ascMM,descMM,tickStepMM:s.script==='Copperplate'?Math.max(xMM*.9,3):effective,tickAnchorS:span?.sStart,actualNibMM:nib});
  const topBase=guideSet.ascLine,topLen=lengthPoly(topBase),topX=s.topBandScript==='Copperplate'?topSize:topSize*s.xNib,topAsc=s.topBandScript==='Copperplate'?topSize*1.25:topSize*s.ascNib,topCap=s.topBandScript==='Copperplate'?topX*1.05:(SCRIPT_DEFAULTS.TexturaQuadrata?.capHeight??7)*topSize,topRun=bandRun(s.topText,s.topBandScript,topSize,effectiveTop),topLayout=computeCurvedTitleLayout(topRun,topBase,topLen,topX,effectiveTop,topCap,s.topBandScript,s.align),topSpan=spanOf(topLayout,topLen),topGuide=buildGuideSet(s.topBandScript==='Copperplate'?'copperplate':'blackletter',{baseline:topBase,xMM:topX,ascMM:topAsc,descMM:0,tickStepMM:s.topBandScript==='Copperplate'?Math.max(topX*.9,3):effectiveTop,tickAnchorS:topSpan?.sStart,actualNibMM:topSize});
  const bottomX=s.bottomBandScript==='Copperplate'?bottomSize:bottomSize*s.xNib,bottomDesc=s.bottomBandScript==='Copperplate'?bottomSize*1.25:bottomSize*s.descNib,bottomCap=s.bottomBandScript==='Copperplate'?bottomX*1.05:(SCRIPT_DEFAULTS.TexturaQuadrata?.capHeight??7)*bottomSize,bottomBase=offset(guideSet.descLine,bottomX),bottomLen=lengthPoly(bottomBase),bottomRun=bandRun(s.bottomText,s.bottomBandScript,bottomSize,effectiveBottom),bottomLayout=computeCurvedTitleLayout(bottomRun,bottomBase,bottomLen,bottomX,effectiveBottom,bottomCap,s.bottomBandScript,s.align),bottomSpan=spanOf(bottomLayout,bottomLen),bottomGuide=buildGuideSet(s.bottomBandScript==='Copperplate'?'copperplate':'blackletter',{baseline:bottomBase,xMM:bottomX,ascMM:0,descMM:bottomDesc,tickStepMM:s.bottomBandScript==='Copperplate'?Math.max(bottomX*.9,3):effectiveBottom,tickAnchorS:bottomSpan?.sStart,actualNibMM:bottomSize});
  const topOuter=s.topBandEnabled?topGuide.ascLine:guideSet.ascLine,bottomOuter=s.bottomBandEnabled?bottomGuide.descLine:guideSet.descLine;
  const visiblePoints=[...guideSet.ascLine,...guideSet.waistLine,...guideSet.baseLine,...guideSet.descLine,...(s.topBandEnabled?[...topGuide.ascLine,...topGuide.waistLine,...topGuide.baseLine]:[]),...(s.bottomBandEnabled?[...bottomGuide.waistLine,...bottomGuide.baseLine,...bottomGuide.descLine]:[])];
  return{baseline,arcLen,layout,guideSet,spanPoly:spanPolygon(span,baseline,arcLen,xMM,effective,s.script),midAscPts:s.script==='Copperplate'?offset(baseline,-(xMM+ascMM*.5)):null,midDescPts:s.script==='Copperplate'?offset(baseline,descMM*.5):null,top:{enabled:s.topBandEnabled,layout:topLayout,guideSet:topGuide,arcLen:topLen,xMM:topX,spanPoly:s.topBandEnabled&&s.topText.trim()?spanPolygon(topSpan,topGuide.baseLine,topLen,topX,effectiveTop,s.topBandScript):null,clip:bandPoly(topGuide.baseLine,topGuide.ascLine)},bottom:{enabled:s.bottomBandEnabled,layout:bottomLayout,guideSet:bottomGuide,arcLen:bottomLen,xMM:bottomX,spanPoly:s.bottomBandEnabled&&s.bottomText.trim()?spanPolygon(bottomSpan,bottomGuide.baseLine,bottomLen,bottomX,effectiveBottom,s.bottomBandScript):null,clip:bandPoly(bottomGuide.waistLine,bottomGuide.descLine)},xMM,script:s.script,curveLength:arcLen,scriptLength:layout.needed,overBy:layout.overBy,visualBounds:boundsOfPoints(visiblePoints),footprintD:bandPoly(topOuter,bottomOuter)};
}
