'use client';
import DisclosureSection from '@/components/layout/DisclosureSection';
import { buildCurvedTitleModel } from '@/lib/curved-title/model';
import type { CopperplateRatioPreset, CurvedTitleSettings } from '@/lib/curved-title/settings';
import type { CurvePresetId } from '@/lib/curve-helpers';
import type { ScriptId } from '@/lib/scripts';

const input='w-full rounded-md border border-slate-300 px-2 py-1.5 text-sm',section='xl:w-[300px] xl:self-start';
const curves:[CurvePresetId,string][]=[['simpleArch','Simple Arch'],['highArch','High Arch'],['shallowArch','Shallow Arch'],['compoundArch','Compound Arch'],['zanerian','Zanerian Resolution']];
const scripts:[ScriptId,string][]=[['Copperplate','Copperplate'],['Fraktur','Fraktur'],['TexturaQuadrata','Textura Quadrata']];
function Field({label,value,onChange,min,step=.5}:{label:string;value:number|string;onChange:(v:string)=>void;min?:number;step?:number}){return <label className="block space-y-1 text-xs font-medium text-slate-600">{label}<input className={input} type="number" value={value} min={min} step={step} onChange={e=>onChange(e.target.value)}/></label>}
function Select<T extends string>({label,value,options,onChange}:{label:string;value:T;options:[T,string][];onChange:(v:T)=>void}){return <label className="block space-y-1 text-xs font-medium text-slate-600">{label}<select className={input} value={value} onChange={e=>onChange(e.target.value as T)}>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="flex items-center justify-between gap-3 text-sm text-slate-700"><span>{label}</span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="accent-indigo-600"/></label>}

export default function CurvedTitleSettingsPanel({value,box,paddingMM,onPaddingChange,onChange}:{value:CurvedTitleSettings;box:{w:number;h:number};paddingMM:number;onPaddingChange:(v:number)=>void;onChange:(v:CurvedTitleSettings)=>void}){
 const patch=<K extends keyof CurvedTitleSettings>(key:K,v:CurvedTitleSettings[K])=>onChange({...value,[key]:v});const model=buildCurvedTitleModel(box,value);
 return <>
  <DisclosureSection title="Basics" defaultOpen className={section}><div className="space-y-3"><Field label="Padding (mm)" value={paddingMM} min={0} onChange={v=>onPaddingChange(Math.max(0,Number(v)||0))}/><Select label="Curve preset" value={value.curve} options={curves} onChange={v=>patch('curve',v)}/><Toggle label="Flip curve" checked={value.flipCurve} onChange={v=>patch('flipCurve',v)}/><Toggle label="Transparent whitespace" checked={value.transparentWhitespace ?? true} onChange={v=>patch('transparentWhitespace',v)}/><p className="-mt-2 text-xs text-slate-500">Allow lower layers to show through empty areas around the curved guides.</p><Select label="Text alignment" value={value.align} options={[['start','Start'],['center','Centered'],['end','End']]} onChange={v=>patch('align',v)}/><label className="block space-y-1 text-xs font-medium text-slate-600">Title text<textarea className={input} rows={2} value={value.text} onChange={e=>patch('text',e.target.value)}/></label></div></DisclosureSection>
  <DisclosureSection title="Script Details" defaultOpen className={section}><div className="space-y-3"><Select label="Script" value={value.script} options={scripts} onChange={v=>patch('script',v)}/>{value.script==='Copperplate'?<><Field label="x-height (mm)" value={value.xHeightMM} min={.5} onChange={v=>patch('xHeightMM',Number(v)||.5)}/><Select label="Capital style" value={value.capStyle} options={[['simple','Simple'],['flourished','Flourished']]} onChange={v=>patch('capStyle',v)}/><Select label="Guide ratio" value={value.copperplateRatioPreset} options={[['2:1:2','2:1:2'],['3:2:3','3:2:3'],['1:1:1','1:1:1'],['custom','Custom']]} onChange={v=>patch('copperplateRatioPreset',v as CopperplateRatioPreset)}/>{value.copperplateRatioPreset==='custom'&&<div className="grid grid-cols-3 gap-2"><Field label="Desc" value={value.copperplateDescUnitsText} min={.1} onChange={v=>patch('copperplateDescUnitsText',v)}/><Field label="X" value={value.copperplateXUnitsText} min={.1} onChange={v=>patch('copperplateXUnitsText',v)}/><Field label="Asc" value={value.copperplateAscUnitsText} min={.1} onChange={v=>patch('copperplateAscUnitsText',v)}/></div>}<Toggle label="Use calibration" checked={value.useCalibration} onChange={v=>patch('useCalibration',v)}/>{value.useCalibration&&<><Field label="Calibration word (mm)" value={value.calWordLowerMM} min={0} onChange={v=>patch('calWordLowerMM',v)}/><Field label="Double-letter word (mm)" value={value.calWordDoubleMM} min={0} onChange={v=>patch('calWordDoubleMM',v)}/><Field label="Width scale" value={value.userScaleFactor} min={.7} step={.01} onChange={v=>patch('userScaleFactor',Number(v)||1)}/><Field label="Space scale" value={value.userSpaceFactor} min={.5} step={.01} onChange={v=>patch('userSpaceFactor',Number(v)||1)}/></>}</>:<><Field label="Nib size (mm)" value={value.nibText} min={.1} onChange={v=>patch('nibText',v)}/><Select label="Pen angle" value={String(value.penAngleDeg) as '35'|'40'|'45'} options={[['35','35°'],['40','40°'],['45','45°']]} onChange={v=>patch('penAngleDeg',Number(v) as 35|40|45)}/><div className="grid grid-cols-3 gap-2"><Field label="X nibs" value={value.xNib} min={1} onChange={v=>patch('xNib',Number(v)||1)}/><Field label="Asc nibs" value={value.ascNib} min={0} onChange={v=>patch('ascNib',Number(v)||0)}/><Field label="Desc nibs" value={value.descNib} min={0} onChange={v=>patch('descNib',Number(v)||0)}/></div></>}</div></DisclosureSection>
  <DisclosureSection title="Additional Bands" className={section}><div className="space-y-4">{(['top','bottom'] as const).map(side=>{const enabled=side==='top'?value.topBandEnabled:value.bottomBandEnabled;return <div key={side} className="space-y-3 border-b border-slate-100 pb-3"><Toggle label={`${side==='top'?'Top':'Bottom'} band`} checked={enabled} onChange={v=>patch(side==='top'?'topBandEnabled':'bottomBandEnabled',v)}/>{enabled&&<><label className="block space-y-1 text-xs font-medium text-slate-600">Text<input className={input} value={side==='top'?value.topText:value.bottomText} onChange={e=>patch(side==='top'?'topText':'bottomText',e.target.value)}/></label><Select label="Script" value={side==='top'?value.topBandScript:value.bottomBandScript} options={scripts} onChange={v=>patch(side==='top'?'topBandScript':'bottomBandScript',v)}/><Field label={(side==='top'?value.topBandScript:value.bottomBandScript)==='Copperplate'?'x-height (mm)':'Nib size (mm)'} value={side==='top'?value.topBandSizeText:value.bottomBandSizeText} min={.1} onChange={v=>patch(side==='top'?'topBandSizeText':'bottomBandSizeText',v)}/></>}</div>})}</div></DisclosureSection>
  <DisclosureSection title="Curve & Guides" defaultOpen className={section}><div className="space-y-3"><label className="block space-y-2 text-xs font-medium text-slate-700"><span>Rotation (°) <span className="text-indigo-600">{value.rotation}°</span></span><input type="range" min={-180} max={180} step={1} value={value.rotation} onChange={e=>patch('rotation',Number(e.target.value))} className="w-full" /></label><label className="block space-y-2 text-xs font-medium text-slate-700"><span>Scale (%) <span className="text-indigo-600">{value.scale}%</span></span><input type="range" min={60} max={140} step={1} value={value.scale} onChange={e=>patch('scale',Number(e.target.value))} className="w-full" /></label><button type="button" className="rounded-md border border-slate-300 bg-white px-3 py-1.5 text-sm hover:bg-slate-50" onClick={()=>onChange({...value,rotation:0,scale:100})}>Reset rotation &amp; scale</button><Toggle label="Show letter bounding boxes" checked={value.showBoxes} onChange={v=>patch('showBoxes',v)}/><Toggle label="Show title span fill" checked={value.showSpanFill} onChange={v=>patch('showSpanFill',v)}/><div className="rounded-md bg-slate-50 p-2 text-xs text-slate-600"><div>Curve length: {model.curveLength.toFixed(1)} mm</div><div>Script length: {model.scriptLength.toFixed(1)} mm</div>{model.overBy>0&&<div className="mt-1 font-medium text-rose-600">Title exceeds curve by {model.overBy.toFixed(1)} mm.</div>}</div></div></DisclosureSection>
 </>;
}
